facts = ["1. Ants are strong little devils! As a matter of fact, they can carry 50 times their own body weight! How’s that for a workout?",
 "2. The soldier ant is, quite literally, a soldier for the Queen. They use their heads to block entrances, stopping intruders from entering the nest.",
 "3. There are a whopping 12,000 species of ants on our planet.",
 "4. They have a larger muscle to body ratio than humans.",
 "5. If you added the mass of all the humans in the world and all the ants in the world, they would be equal.",
 "6. They are helpful critters! They often carry other insects from plant to plant. But don’t be fooled, they just want the insects’ nectar!",
 "7. Ants are enslavers! They often ‘kidnap’ ants from other colonies and force them to do their work.",
 "8. It is believed that ants have existed on this planet for 130 million years.",
 "9. There is a species of ant named after Harrison Ford called ‘Pheidole harrisonfordi’. The perks of being an environmentalist!",
 "10. They are the worlds’ first farmers. They have had agriculture longer than human beings!",
 "11. They forage by following other ants trails of pheromones to food sources.",
 "12. Once a queen has mated, her wings fall off.",
 "13. All of the workers in an ant colony are females. These females are all sterile.",
 "14. Male ants have wings and often fly in swarms in order to find mates.",
 "15. The world’s biggest ant is the bullet ant, which is found in the Panama jungle. These critters can grow up to 1.6 inches. Eeek!",
 "16. The sole purpose of a male ant in life is to mate. Once it has spread its seed, it will die.",
 "17. Ants have already survived the ice age! Despite their teeny tiny size, it seems they were more resilient than dinosaurs.",
 "18. Ants have succeeded in world domination! These insects can be found in every single continent except for the artic and Antarctica.",
 "19. There are over 10,000,000,000,000,000 ants on the earth right now.",
 "20. A prehistoric ant was discovered that had a wing span of six inches. It is known as the Titanomymra giganteum and is the biggest ant to have ever existed.",
 "21. In tropical regions, ants make up 25% of the mass of all fauna.",
 "22. The average black garden ant has a lifespan longer than the average dog. (15 years).",
 "23. The correct collective noun for a group of ants is a swarm of ants.",
 "24. Ants can create superbrains! Although they may be small, they can come together as huge groups and use their intellect as a whole. Freaky!",
 "25. The butt of an Australian green ant has a similar taste to lime.",
 "26. Some ant nests can go as deep as two feet underground.",
 "27. Ants can kill! The Australian bulldog ant is officially the world’s most dangerous ant and has caused 3 deaths since the 1930s.",
 "28. Fire ant colonies in the Amazon Rainforest link their legs together to create a ‘raft’. This allows them to float down rivers and travel through the forest.",
 "29. There are three types of ants in a colony; the queen, the major worker and the lesser worker. The queen is the largest and the lesser worker the smallest.",
 "30. 20 percent of ants in a colony do absolutely nothing! Lazy things…",
 "31. Queen ants can live three decades. That’s longer than any other insect!",
 "32. The bullet ant has the most painful sting of any insect. The effect of it’s venom-filled sting can last up to 24 hours. It has been compared to putting your finger in a 240 volt socket! Ouch!",
 "33. Soldier ants ‘steal’ eggs from other colonies. Once they hatch, the baby ants will be used as slaves.",
 "34. Some Native American tribes practice initiation rituals in which they force young men to be bitten consecutively by bullet ants.",
 "35. They are super patriotic! When the queen dies, the rest of the colony will die within a few months.",
 "36. Ants belong to the insect group Hymenoptera, which also includes wasps and bees.",
 "37. The role of the Queen is to lay tens of thousands of eggs, ensuring that the colony remains strong and mighty.",
 "38. Ants ‘hear’ through vibrations. As a matter of fact, they don’t even have ears!",
 "39. Ants have no lungs! They simply have tiny holes from which oxygen enters and carbon dioxide leaves.",
 "40. Carpenter ants can be a total pain to your home! These guys build their nests in wood, which isn’t so great when it comes to your ceiling beams!",
 "41. Some ants stink! The odorous house ant gives off a not-so-lovely stench of rotten coconuts.",
 "42. Female worker ants can travel as long far as 200 metres from their nests. That’s a long way when you’re that small!",
 "43. The sting of a bullet ant is powerful enough to paralyse a tarantula.",
 "44. An ant the size of a human could run as fast as a race horse.",
 "45. A colony of 40,000 ants is collectively as intelligent as a human being.",
 "46. Ants have two stomachs, one for their own food and one to feed others.",
 "47. Australian green ant colonies can have nests spanning over twelve trees.",
 "48. Ant eggs survive by consuming the queen ant’s saliva. Yum!",
 "49. A ‘super colony’ is a giant ant colony and can contain up to 300 million individual ants.",
 "50. Some ants are nomads. These wondering critters are army ants and walk alone in between collecting food and attacking rival colonies.",
 "51. There are one million ants for every human on our planet.",
 "52. Ants can swim. Gosh… is there anything they can’t do?",
 "53. They are officially the world’s smartest insects and have a whopping 250,000 brain cells.",
 "54. Leafcutter ants are farmers! They grow mushrooms through secreting antibiotics, which enhances mould growth.",
 "55. Army ants do not live in a nest. These ants are always on the move and are found in Central and South America.",
 "56. Ants can go to war with rival colonies for weeks at a time.",
 "57. The Queen ant certainly doesn’t have blue blood! As a matter of fact, ant blood is completely colorless.",
 "58. The world’s largest ant colony spans 600 miles and can be found in Southern California.",
 "59. Driver ants are scary. These predators work in mass groups to consume everything in their paths. They have been known to consume tethered horses and even human infants.",
 "60. Although often mistaken for them, termites are not ants! As a matter of fact, they are actually more similar to cockroaches than ants.",
 "61. Ants teach each other! They are the only non-mammals who can learn via interaction.",
 "62. Ants are able to navigate using the earth’s magnetic field. Who needs sat nav?",
 "63. Feeling hungry? Ant eggs are a delicacy in Mexico. The dish, ‘escamoles’, sounds gross, but is actually very expensive.",
 "64. What is the fastest animal in the world? A cheetah? Apparently a certain ant species holds the record.",
 "65. Each year, ants move approximately 50 tons of soil per square mile.",
 "66. As ants don’t have lungs, then can survive a whole day underwater.",
 "67. The average fire ant sleeps around 9 hours per day.",
 "68. Thought there was just pavement ants in your area? There is 1,000 species of ants currently dwelling in the United States.",
 "69. If an egg is fertilised, a female ant develops. If the egg is left unfertilised, a male ant hatches.",
 "70. After ant eggs hatch, the larvae are raised by the worker ants. So… that’s basically ant day care right?",
 "71. Ants have compound eyes, which allow them to see movement very well.",
 "72. A swarm of army ants can be as long as 100m in length. Scary!",
 "73. The world’s smallest ant is the Pharoah ant, which is a teeny 2mm long.",
 "74. The Australian jumping spider disguises itself as a green ant and sneaks into the nest in order to feed on the larvae. This process is known as chemical mimicry.",
 "75. The strongest ant is the leafcutter ant, which can lift 50 times its body weight.",
 "76. The evolution of the ant is believed to be due to flowering plants providing more complex ground habitats. This occurred 100 million years ago.",
 "77. Although Hawaii is a detached island, it still has ants! There are currently 50 species of these ants crawling around this island and none of them are native.",
 "78. The queen actually has very little control over the colony. Ants work as a whole colony cognitively.",
 "79. The bite of a bulldog ant can kill a human in 15 minutes.",
 "80. Most ant species only have one queen per colony, but the red imported fire ant and the Argentine ant have been known to have two.",
 "81. Ants can smell with their antenna! Who needs a nose?",
 "82. The jaws of an aunt are much like a pair of scissors; they open sideways.",
 "83. Ants are pretty darn tidy. Worker ants have been known to take rubbish outside the nest to a dumping point!",
 "84. Each ant colony has its own special scent. This way, they can smell intruders!",
 "85. Birds love black ants! They often put them in their feathers, as they secrete formic acid, which eliminates parasites.",
 "86. If it’s a bit chilly outside, worker ants will move the larvae further into the nest.",
 "87. Honeypot ants are literally living honeypots! These greedy critters spend their days feasting on food, making their bellies swell into bags of sweet liquid. They then regurgitate this to feed others in the colony.",
 "88. Ants are the sheepdogs of the insect world and herd aphids, protecting them from predators.",
 "89. The carpenter ant can self destruct to save others! It contracts its body to rupture their gland and spray toxic liquid at its enemies.",
 "90. There is a species of vampire ant! They live in Madagascar and feed by biting holes into their larvae and drinking their blood.",
 "91. A larvae will become a queen if it is well nourished and its parent is of a sexually reproductive colony.",
 "92. Ants are also in the mining business! In Arizona, ants find garnets and drag them to the surface.",
 "93. An ant that is destined to become a Queen ant is suitably called a Princess ant.",
 "94. When an ant dies, it releases a chemical that communicates to the other ants to move it to a burial ground.",
 "95. A skydiver was saved by ants! Joan Murray landed on a fire ant nest and the 200 shocks the ants gave her kept her heart beating.",
 "96. East African Indigenous tribes use ants in medicine. They get the ant to produce two bites on either side of a cut to help it heal. The power of the ant’s jaw creates a seal.",
 "97. Wings ants are most likely to result from a fully established colony.",
 "98. Some say that the bite of a bullet ant is as painful as being shot. Guess they’re called bullet ants for a reason…",
 "99. Ants eyes are made of a combination of small eyes.",
 "100. Forget human zombies, ant zombies actually exist! This is caused by a type of fungus that infects the ants and takes control of them. Luckily, ants can sense this and often kill the infected colony member."]